# Pre-commit hooks configuration
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Version consistency check
  - repo: local
    hooks:
      - id: check-version-sync
        name: Check version consistency
        entry: scripts/check_version_sync.sh
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|ytmpd/__init__\.py)$

  # Python code formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: ['--fix=lf']
